services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicles-service
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=didit-db
      - DB_PORT=3306
      - DB_DATABASE=db_kendaraan
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      didit-db:
        condition: service_healthy

  didit-db:
    image: mysql:8.0
    container_name: didit-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db_kendaraan
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
